#!/usr/bin/env python3
"""
My Insta Downloader Bot - Full Featured + Log Media Forwarding
Instagram & TikTok Downloader with Profile, Posts, Reels, Stories, Highlights, Analytics
Deploy: Koyeb (Free Tier)
"""

import os
import sys
import re
import json
import logging
import tempfile
import asyncio
import shutil
from concurrent.futures import ThreadPoolExecutor
from threading import Thread
from http.server import BaseHTTPRequestHandler, HTTPServer
from datetime import datetime
from typing import Optional, Tuple, List, Dict, Any

from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup, User
from telegram.ext import (
    Application, CommandHandler, MessageHandler, CallbackQueryHandler,
    ContextTypes, filters, ConversationHandler
)
import yt_dlp
import requests

# ==================== CONFIG ====================
BOT_TOKEN = os.getenv("BOT_TOKEN", "").strip()
ADMIN_IDS = [x.strip() for x in os.getenv("ADMIN_IDS", "").split(",") if x.strip()]
LOG_CHANNEL_ID = os.getenv("LOG_CHANNEL_ID", "").strip()
IG_SESSION_ID = os.getenv("IG_SESSION_ID", "").strip()
BAN_LIST: set = set()

if not BOT_TOKEN:
    logging.error("❌ BOT_TOKEN not set! Exiting.")
    sys.exit(1)

# ==================== LOGGING ====================
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO
)
logger = logging.getLogger(__name__)

# ==================== THREAD POOL ====================
executor = ThreadPoolExecutor(max_workers=4)

# ==================== COOKIES ====================
COOKIE_FILE = "/tmp/ig_cookies.txt"

def init_cookies() -> bool:
    """Create cookie file from IG_SESSION_ID env var."""
    if not IG_SESSION_ID:
        return False
    try:
        with open(COOKIE_FILE, "w") as f:
            f.write(f"""# Netscape HTTP Cookie File
# Generated by InstaBot
.instagram.com\tTRUE\t/\tTRUE\t0\tcsrftoken\t{IG_SESSION_ID[:16]}
.instagram.com\tTRUE\t/\tTRUE\t0\tsessionid\t{IG_SESSION_ID}
""")
        logger.info("✅ Instagram cookies initialized from IG_SESSION_ID")
        return True
    except Exception as e:
        logger.error(f"Cookie init error: {e}")
        return False

def cookies_ready() -> bool:
    return os.path.exists(COOKIE_FILE) and os.path.getsize(COOKIE_FILE) > 0

# ==================== HEALTH SERVER (Koyeb) ====================
class HealthHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-type", "text/plain")
        self.end_headers()
        self.wfile.write(b"OK - Bot Running")
    def log_message(self, format, *args):
        pass

def start_health_server():
    try:
        srv = HTTPServer(("0.0.0.0", 8080), HealthHandler)
        Thread(target=srv.serve_forever, daemon=True).start()
        logger.info("🩺 Health server running on 0.0.0.0:8080")
    except Exception as e:
        logger.warning(f"Health server failed: {e}")

# ==================== ADMIN / LOG HELPERS ====================
def is_admin(user_id: int) -> bool:
    return str(user_id) in ADMIN_IDS

def is_banned(user_id: int) -> bool:
    return str(user_id) in BAN_LIST

async def send_log_text(context: ContextTypes.DEFAULT_TYPE, text: str):
    """Send text log to admin channel."""
    if not LOG_CHANNEL_ID:
        return
    try:
        await context.bot.send_message(
            chat_id=LOG_CHANNEL_ID,
            text=text,
            parse_mode="HTML"
        )
    except Exception as e:
        logger.warning(f"Log channel text error: {e}")

async def send_log_media(context: ContextTypes.DEFAULT_TYPE, filepath: str, caption: str, is_video: bool = True):
    """Send media file to log channel."""
    if not LOG_CHANNEL_ID:
        return
    if not os.path.exists(filepath):
        return
    try:
        if is_video and filepath.lower().endswith(('.mp4', '.mov', '.mkv')):
            with open(filepath, 'rb') as f:
                await context.bot.send_video(
                    chat_id=LOG_CHANNEL_ID,
                    video=f,
                    caption=caption[:1024],
                    supports_streaming=True
                )
        elif filepath.lower().endswith(('.jpg', '.jpeg', '.png', '.webp', '.gif')):
            with open(filepath, 'rb') as f:
                await context.bot.send_photo(
                    chat_id=LOG_CHANNEL_ID,
                    photo=f,
                    caption=caption[:1024]
                )
        else:
            with open(filepath, 'rb') as f:
                await context.bot.send_document(
                    chat_id=LOG_CHANNEL_ID,
                    document=f,
                    caption=caption[:1024]
                )
    except Exception as e:
        logger.warning(f"Log media send error: {e}")
        try:
            with open(filepath, 'rb') as f:
                await context.bot.send_document(
                    chat_id=LOG_CHANNEL_ID,
                    document=f,
                    caption=f"📎 Log Media\n{caption[:900]}"
                )
        except Exception as e2:
            logger.error(f"Log media fallback failed: {e2}")
            await send_log_text(context, f"❌ Could not send media to log channel.\n{caption[:1000]}")

async def log_user_message(update: Update, context: ContextTypes.DEFAULT_TYPE, extra: str = ""):
    user = update.effective_user
    text = update.effective_message.text if update.effective_message else "[no text]"
    msg = (
        f"📥 <b>New User Request</b>\n"
        f"⏰ {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        f"👤 <b>User:</b> {user.first_name} (@{user.username or 'N/A'})\n"
        f"🆔 <b>ID:</b> <code>{user.id}</code>\n"
        f"💬 <b>Message:</b> <code>{text[:500]}</code>"
    )
    if extra:
        msg += f"\n📝 <b>Extra:</b> {extra}"
    await send_log_text(context, msg)

async def log_download_success(update: Update, context: ContextTypes.DEFAULT_TYPE, original_url: str, filepath: str, info: dict, is_tiktok: bool):
    """Log full media to log channel on success."""
    if not LOG_CHANNEL_ID:
        return
    user = update.effective_user
    is_video = True
    if filepath.lower().endswith(('.jpg', '.jpeg', '.png', '.webp', '.gif')):
        is_video = False
    elif filepath.lower().endswith(('.mp4', '.mov', '.mkv')):
        is_video = True
    else:
        is_video = False
    
    platform = "🎵 TikTok" if is_tiktok else "📸 Instagram"
    title = info.get("title", "No title")[:100] if info else "No title"
    uploader = info.get("uploader", "Unknown")[:50] if info else "Unknown"
    size_mb = os.path.getsize(filepath) / (1024 * 1024) if os.path.exists(filepath) else 0
    
    caption = (
        f"✅ <b>Download Successful</b>\n"
        f"⏰ {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        f"{platform}\n"
        f"🔗 <b>Original Link:</b>\n<code>{original_url}</code>\n\n"
        f"📝 <b>Title:</b> {title}\n"
        f"👤 <b>Uploader:</b> {uploader}\n"
        f"📦 <b>Size:</b> {size_mb:.1f} MB\n\n"
        f"👤 <b>Requested By:</b> {user.first_name} (@{user.username or 'N/A'})\n"
        f"🆔 <b>User ID:</b> <code>{user.id}</code>"
    )
    
    await send_log_media(context, filepath, caption, is_video)

async def log_download_failure(update: Update, context: ContextTypes.DEFAULT_TYPE, original_url: str, error: str, is_tiktok: bool):
    """Log failed download to channel."""
    if not LOG_CHANNEL_ID:
        return
    user = update.effective_user
    platform = "🎵 TikTok" if is_tiktok else "📸 Instagram"
    msg = (
        f"❌ <b>Download Failed</b>\n"
        f"⏰ {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        f"{platform}\n"
        f"🔗 <b>Link:</b>\n<code>{original_url}</code>\n\n"
        f"⚠️ <b>Error:</b>\n<code>{error[:1000]}</code>\n\n"
        f"👤 <b>User:</b> {user.first_name} (@{user.username or 'N/A'})\n"
        f"🆔 <b>User ID:</b> <code>{user.id}</code>"
    )
    await send_log_text(context, msg)

# ==================== YT-DLP HELPERS ====================
def run_yt_dlp_info(url: str, cookiefile: Optional[str] = None) -> Tuple[Optional[dict], Optional[str]]:
    """Extract info without downloading."""
    opts = {
        'quiet': True,
        'no_warnings': True,
        'skip_download': True,
    }
    if cookiefile and os.path.exists(cookiefile):
        opts['cookiefile'] = cookiefile
    try:
        with yt_dlp.YoutubeDL(opts) as ydl:
            info = ydl.extract_info(url, download=False)
            return info, None
    except Exception as e:
        return None, str(e)

def run_yt_dlp_download(url: str, cookiefile: Optional[str] = None) -> Tuple[Optional[dict], Optional[str]]:
    """Download media, return info and filepath."""
    out_dir = tempfile.mkdtemp()
    opts = {
        'outtmpl': os.path.join(out_dir, '%(id)s.%(ext)s'),
        'quiet': True,
        'no_warnings': True,
        'format': 'best[filesize<50M]/best',
        'max_filesize': 50 * 1024 * 1024,
    }
    if cookiefile and os.path.exists(cookiefile):
        opts['cookiefile'] = cookiefile
    try:
        with yt_dlp.YoutubeDL(opts) as ydl:
            info = ydl.extract_info(url, download=True)
            filepath = ydl.prepare_filename(info)
            # yt-dlp sometimes changes extension (e.g., mp4 -> jpg for images)
            if not os.path.exists(filepath):
                base = os.path.splitext(filepath)[0]
                for f in os.listdir(out_dir):
                    if f.startswith(os.path.basename(base)):
                        filepath = os.path.join(out_dir, f)
                        break
            if os.path.exists(filepath) and os.path.getsize(filepath) > 0:
                return info, filepath
            return info, None
    except Exception as e:
        return None, str(e)

async def safe_send_media(update: Update, filepath: str, caption: str, is_video: bool = True):
    """Safely send media, fallback to document."""
    try:
        if is_video and filepath.lower().endswith(('.mp4', '.mov', '.mkv')):
            with open(filepath, 'rb') as f:
                await update.message.reply_video(video=f, caption=caption[:1024], supports_streaming=True)
        elif filepath.lower().endswith(('.jpg', '.jpeg', '.png', '.webp', '.gif')):
            with open(filepath, 'rb') as f:
                await update.message.reply_photo(photo=f, caption=caption[:1024])
        else:
            with open(filepath, 'rb') as f:
                await update.message.reply_document(document=f, caption=caption[:1024])
        return True
    except Exception as e:
        logger.error(f"Send media error: {e}")
        try:
            with open(filepath, 'rb') as f:
                await update.message.reply_document(document=f, caption=caption[:1024])
            return True
        except Exception as e2:
            logger.error(f"Document send error: {e2}")
            return False

# ==================== INSTAGRAM API HELPERS ====================
def instagram_headers() -> dict:
    return {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
        "Accept": "*/*",
        "X-IG-App-ID": "936619743392459",
        "X-Requested-With": "XMLHttpRequest",
        "Referer": "https://www.instagram.com/",
    }

def fetch_profile_info(username: str) -> Optional[dict]:
    """Try to fetch profile via web API. Returns None if blocked."""
    url = f"https://www.instagram.com/api/v1/users/web_profile_info/?username={username}"
    headers = instagram_headers()
    try:
        resp = requests.get(url, headers=headers, timeout=15, cookies={'sessionid': IG_SESSION_ID} if IG_SESSION_ID else None)
        if resp.status_code == 200:
            data = resp.json()
            return data.get("data", {}).get("user", {})
    except Exception as e:
        logger.warning(f"Profile fetch failed: {e}")
    return None

# ==================== BOT COMMANDS ====================
async def start_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    if is_banned(user.id):
        return
    
    text = (
        f"👋 <b>Welcome {user.first_name}!</b>\n\n"
        f"📥 <b>My Insta Downloader Bot</b>\n\n"
        f"<b>Download kaise karein:</b>\n"
        f"1. Instagram/TikTok par post/reel kholein\n"
        f"2. Share button dabao → 'Copy Link'\n"
        f"3. Yahan paste karo!\n\n"
        f"✅ <b>Supported:</b>\n"
        f"• Instagram Posts, Reels, Stories\n"
        f"• TikTok Videos (no watermark!)\n\n"
        f"Ya menu se choose karo 👇"
    )
    keyboard = [
        [InlineKeyboardButton("📥 Download Guide", callback_data="help")],
        [InlineKeyboardButton("👤 Profile", callback_data="menu_profile"),
         InlineKeyboardButton("📸 Posts", callback_data="menu_posts")],
        [InlineKeyboardButton("🎬 Reels", callback_data="menu_reels"),
         InlineKeyboardButton("📖 Stories", callback_data="menu_stories")],
        [InlineKeyboardButton("🌟 Highlights", callback_data="menu_highlights"),
         InlineKeyboardButton("📊 Analytics", callback_data="menu_analytics")],
    ]
    await update.message.reply_text(text, reply_markup=InlineKeyboardMarkup(keyboard), parse_mode="HTML")
    await send_log_text(context,
        f"🆕 <b>New User Started</b>\n"
        f"👤 {user.first_name} (@{user.username or 'N/A'})\n"
        f"🆔 <code>{user.id}</code>\n"
        f"⏰ {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )

async def help_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    text = (
        "<b>🤖 My Insta Downloader - Help</b>\n\n"
        "<b>Direct Download:</b>\n"
        "Just paste any Instagram or TikTok link!\n\n"
        "<b>Commands:</b>\n"
        "/start - Start bot\n"
        "/help - This message\n"
        "/setcookie - How to set Instagram cookie\n"
        "/profile username - Profile info\n"
        "/posts username - Latest 9 posts\n"
        "/reels username - Latest 6 reels\n"
        "/stories username - Active stories\n"
        "/highlights username - Story highlights\n"
        "/analytics username - Profile analytics\n\n"
        "<b>Admin Only:</b>\n"
        "/stats - Bot statistics\n"
        "/broadcast message - Broadcast to all users\n"
        "/ban user_id - Ban a user\n"
        "/unban user_id - Unban a user\n\n"
        "<i>⚠️ Note: Instagram sometimes blocks cloud servers.\n"
        "If downloads fail, set your cookie via /setcookie or Koyeb env IG_SESSION_ID.</i>"
    )
    await update.message.reply_text(text, parse_mode="HTML")

async def setcookie_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    text = (
        "🔑 <b>How to get Instagram Session ID:</b>\n\n"
        "1. Login to Instagram in Chrome/Edge on your PC\n"
        "2. Press F12 → Application → Cookies → instagram.com\n"
        "3. Find 'sessionid' and copy its value\n"
        "4. In Koyeb Dashboard:\n"
        "   • Go to your App → Settings → Environment Variables\n"
        "   • Add: Key = <code>IG_SESSION_ID</code>\n"
        "   • Value = your sessionid value\n"
        "5. Redeploy / Restart the app\n\n"
        "⚠️ Without this, Instagram stories, private posts, and profile data won't work!"
    )
    await update.message.reply_text(text, parse_mode="HTML")

# ==================== PROFILE MENU ====================
def profile_keyboard(username: str) -> InlineKeyboardMarkup:
    return InlineKeyboardMarkup([
        [InlineKeyboardButton("👤 Profile Info", callback_data=f"profile:{username}"),
         InlineKeyboardButton("📸 Latest Posts", callback_data=f"posts:{username}")],
        [InlineKeyboardButton("🎬 Latest Reels", callback_data=f"reels:{username}"),
         InlineKeyboardButton("📖 Stories", callback_data=f"stories:{username}")],
        [InlineKeyboardButton("🌟 Highlights", callback_data=f"highlights:{username}"),
         InlineKeyboardButton("📊 Analytics", callback_data=f"analytics:{username}")],
        [InlineKeyboardButton("⬅️ Back", callback_data="menu_main")],
    ])

async def show_profile_menu(update: Update, username: str, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        f"👤 @{username} ke liye options choose karo:",
        reply_markup=profile_keyboard(username)
    )

async def profile_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not context.args:
        await update.message.reply_text("Usage: /profile username\nExample: /profile virat.kohli")
        return
    username = context.args[0].strip().replace("@", "")
    await show_profile_menu(update, username, context)

async def posts_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not context.args:
        await update.message.reply_text("Usage: /posts username")
        return
    username = context.args[0].strip().replace("@", "")
    await process_posts(update, context, username, is_callback=False)

async def reels_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not context.args:
        await update.message.reply_text("Usage: /reels username")
        return
    username = context.args[0].strip().replace("@", "")
    await process_reels(update, context, username, is_callback=False)

async def stories_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not context.args:
        await update.message.reply_text("Usage: /stories username")
        return
    username = context.args[0].strip().replace("@", "")
    await process_stories(update, context, username, is_callback=False)

async def highlights_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not context.args:
        await update.message.reply_text("Usage: /highlights username")
        return
    username = context.args[0].strip().replace("@", "")
    await process_highlights(update, context, username, is_callback=False)

async def analytics_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not context.args:
        await update.message.reply_text("Usage: /analytics username")
        return
    username = context.args[0].strip().replace("@", "")
    await process_analytics(update, context, username, is_callback=False)

# ==================== FEATURE PROCESSORS ====================
async def process_profile(update: Update, context: ContextTypes.DEFAULT_TYPE, username: str, is_callback: bool):
    msg = await (update.callback_query.edit_message_text if is_callback else update.message.reply_text)(
        f"⏳ @{username} ka profile info fetch ho raha hai..."
    )
    
    user_data = fetch_profile_info(username)
    if user_data:
        bio = user_data.get("biography", "N/A")
        full_name = user_data.get("full_name", username)
        followers = user_data.get("edge_followed_by", {}).get("count", "N/A")
        following = user_data.get("edge_follow", {}).get("count", "N/A")
        posts = user_data.get("edge_owner_to_timeline_media", {}).get("count", "N/A")
        is_private = user_data.get("is_private", False)
        is_verified = user_data.get("is_verified", False)
        pic_url = user_data.get("profile_pic_url_hd") or user_data.get("profile_pic_url")
        
        text = (
            f"👤 <b>{full_name}</b> {'✅' if is_verified else ''}\n"
            f"<b>@{username}</b> {'🔒 Private' if is_private else '🌐 Public'}\n\n"
            f"📝 <b>Bio:</b> {bio[:300] if bio else 'N/A'}\n\n"
            f"👥 <b>Followers:</b> {followers}\n"
            f"➡️ <b>Following:</b> {following}\n"
            f"📸 <b>Posts:</b> {posts}"
        )
        if pic_url:
            try:
                await update.effective_chat.send_photo(photo=pic_url, caption=text, parse_mode="HTML")
                if is_callback:
                    await msg.delete()
                return
            except:
                pass
        if is_callback:
            await update.callback_query.edit_message_text(text, parse_mode="HTML", reply_markup=profile_keyboard(username))
        else:
            await update.message.reply_text(text, parse_mode="HTML", reply_markup=profile_keyboard(username))
    else:
        err_text = (
            f"❌ @{username} ka profile info nahi mil paya.\n\n"
            f"Reasons:\n"
            f"• Instagram ne server IP block kiya ho\n"
            f"• Username galat ho\n"
            f"• Account private ho (cookie chahiye)\n\n"
            f"Try karo: /setcookie"
        )
        if is_callback:
            await update.callback_query.edit_message_text(err_text, reply_markup=profile_keyboard(username))
        else:
            await update.message.reply_text(err_text, reply_markup=profile_keyboard(username))

async def process_posts(update: Update, context: ContextTypes.DEFAULT_TYPE, username: str, is_callback: bool):
    msg = await (update.callback_query.edit_message_text if is_callback else update.message.reply_text)(
        f"⏳ @{username} ki latest posts fetch ho rahi hain..."
    )
    url = f"https://instagram.com/{username}"
    info, err = await asyncio.get_event_loop().run_in_executor(executor, run_yt_dlp_info, url, COOKIE_FILE)
    
    if info and info.get("entries"):
        entries = list(info["entries"])[:9]
        text = f"📸 <b>@{username}</b> ki Latest Posts:\n\n"
        for i, entry in enumerate(entries, 1):
            title = entry.get("title", "No title")[:50]
            text += f"{i}. {title}\n🔗 {entry.get('url', 'N/A')}\n\n"
        text += "Direct download ke liye link copy karke bot me paste karo!"
        if is_callback:
            await update.callback_query.edit_message_text(text, parse_mode="HTML", reply_markup=profile_keyboard(username), disable_web_page_preview=True)
        else:
            await update.message.reply_text(text, parse_mode="HTML", reply_markup=profile_keyboard(username), disable_web_page_preview=True)
    else:
        err_text = f"❌ Posts nahi mil payi.\nError: {err or 'Unknown'}\n\n/setcookie try karo!"
        if is_callback:
            await update.callback_query.edit_message_text(err_text, reply_markup=profile_keyboard(username))
        else:
            await update.message.reply_text(err_text, reply_markup=profile_keyboard(username))

async def process_reels(update: Update, context: ContextTypes.DEFAULT_TYPE, username: str, is_callback: bool):
    msg = await (update.callback_query.edit_message_text if is_callback else update.message.reply_text)(
        f"⏳ @{username} ki latest reels fetch ho rahi hain..."
    )
    url = f"https://instagram.com/{username}/reels"
    info, err = await asyncio.get_event_loop().run_in_executor(executor, run_yt_dlp_info, url, COOKIE_FILE)
    
    if info and info.get("entries"):
        entries = list(info["entries"])[:6]
        text = f"🎬 <b>@{username}</b> ki Latest Reels:\n\n"
        for i, entry in enumerate(entries, 1):
            text += f"{i}. {entry.get('title', 'Reel')[:50]}\n🔗 {entry.get('url', 'N/A')}\n\n"
        text += "Direct download ke liye link copy karke paste karo!"
        if is_callback:
            await update.callback_query.edit_message_text(text, parse_mode="HTML", reply_markup=profile_keyboard(username), disable_web_page_preview=True)
        else:
            await update.message.reply_text(text, parse_mode="HTML", reply_markup=profile_keyboard(username), disable_web_page_preview=True)
    else:
        err_text = f"❌ Reels nahi mil payi.\nError: {err or 'Unknown'}\n\n/setcookie try karo!"
        if is_callback:
            await update.callback_query.edit_message_text(err_text, reply_markup=profile_keyboard(username))
        else:
            await update.message.reply_text(err_text, reply_markup=profile_keyboard(username))

async def process_stories(update: Update, context: ContextTypes.DEFAULT_TYPE, username: str, is_callback: bool):
    msg = await (update.callback_query.edit_message_text if is_callback else update.message.reply_text)(
        f"⏳ @{username} ki stories fetch ho rahi hain..."
    )
    if not cookies_ready():
        err_text = "❌ Stories ke liye Instagram login cookie chahiye!\n\n/setcookie se setup karo."
        if is_callback:
            await update.callback_query.edit_message_text(err_text, reply_markup=profile_keyboard(username))
        else:
            await update.message.reply_text(err_text, reply_markup=profile_keyboard(username))
        return
    
    url = f"https://instagram.com/stories/{username}"
    info, err = await asyncio.get_event_loop().run_in_executor(executor, run_yt_dlp_info, url, COOKIE_FILE)
    
    if info and info.get("entries"):
        entries = list(info["entries"])
        text = f"📖 <b>@{username}</b> ki Active Stories ({len(entries)}):\n\n"
        for i, entry in enumerate(entries, 1):
            text += f"{i}. {entry.get('title', 'Story')}\n🔗 {entry.get('url', 'N/A')}\n\n"
        if is_callback:
            await update.callback_query.edit_message_text(text, parse_mode="HTML", reply_markup=profile_keyboard(username), disable_web_page_preview=True)
        else:
            await update.message.reply_text(text, parse_mode="HTML", reply_markup=profile_keyboard(username), disable_web_page_preview=True)
    else:
        err_text = f"❌ Stories nahi mil payi.\nError: {err or 'No active stories / IP blocked'}\n\nCookie fresh hai check karo!"
        if is_callback:
            await update.callback_query.edit_message_text(err_text, reply_markup=profile_keyboard(username))
        else:
            await update.message.reply_text(err_text, reply_markup=profile_keyboard(username))

async def process_highlights(update: Update, context: ContextTypes.DEFAULT_TYPE, username: str, is_callback: bool):
    msg = await (update.callback_query.edit_message_text if is_callback else update.message.reply_text)(
        f"⏳ @{username} ke highlights fetch ho rahe hain..."
    )
    if not cookies_ready():
        err_text = "❌ Highlights ke liye Instagram login cookie chahiye!\n\n/setcookie se setup karo."
        if is_callback:
            await update.callback_query.edit_message_text(err_text, reply_markup=profile_keyboard(username))
        else:
            await update.message.reply_text(err_text, reply_markup=profile_keyboard(username))
        return
    
    text = (
        f"🌟 <b>@{username}</b> Highlights:\n\n"
        f"Highlights download ke liye direct highlight link paste karo.\n"
        f"Format: <code>https://instagram.com/s/aGlnaGxpZ2h0...</code>\n\n"
        f"Ya direct profile link se story download karo."
    )
    if is_callback:
        await update.callback_query.edit_message_text(text, parse_mode="HTML", reply_markup=profile_keyboard(username))
    else:
        await update.message.reply_text(text, parse_mode="HTML", reply_markup=profile_keyboard(username))

async def process_analytics(update: Update, context: ContextTypes.DEFAULT_TYPE, username: str, is_callback: bool):
    msg = await (update.callback_query.edit_message_text if is_callback else update.message.reply_text)(
        f"⏳ @{username} ke analytics calculate ho rahe hain..."
    )
    
    user_data = fetch_profile_info(username)
    if user_data:
        followers = user_data.get("edge_followed_by", {}).get("count", 0)
        following = user_data.get("edge_follow", {}).get("count", 0)
        posts_count = user_data.get("edge_owner_to_timeline_media", {}).get("count", 0)
        media = user_data.get("edge_owner_to_timeline_media", {}).get("edges", [])
        
        total_likes = 0
        total_comments = 0
        video_count = 0
        image_count = 0
        for edge in media[:12]:
            node = edge.get("node", {})
            total_likes += node.get("edge_liked_by", {}).get("count", 0)
            total_comments += node.get("edge_media_to_comment", {}).get("count", 0)
            if node.get("is_video", False):
                video_count += 1
            else:
                image_count += 1
        
        avg_likes = total_likes / len(media) if media else 0
        avg_comments = total_comments / len(media) if media else 0
        engagement = ((avg_likes + avg_comments) / followers * 100) if followers else 0
        
        text = (
            f"📊 <b>@{username} Analytics</b>\n\n"
            f"👥 <b>Followers:</b> {followers:,}\n"
            f"📸 <b>Total Posts:</b> {posts_count:,}\n"
            f"📈 <b>Avg Likes:</b> {avg_likes:,.0f}\n"
            f"💬 <b>Avg Comments:</b> {avg_comments:,.0f}\n"
            f"🔥 <b>Engagement Rate:</b> {engagement:.2f}%\n\n"
            f"🎬 <b>Videos:</b> {video_count}\n"
            f"🖼️ <b>Images:</b> {image_count}"
        )
    else:
        text = (
            f"📊 <b>@{username} Analytics</b>\n\n"
            f"❌ Profile data nahi mil paya.\n"
            f"Cloud IP block ho sakta hai.\n\n"
            f"Koyeb pe deploy hai toh:\n"
            f"• Cookie set karo /setcookie\n"
            f"• Ya local machine pe run karo"
        )
    
    if is_callback:
        await update.callback_query.edit_message_text(text, parse_mode="HTML", reply_markup=profile_keyboard(username))
    else:
        await update.message.reply_text(text, parse_mode="HTML", reply_markup=profile_keyboard(username))

# ==================== CALLBACK HANDLER ====================
async def callback_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()
    data = query.data
    
    if data == "help":
        await help_cmd(update, context)
        return
    
    if data == "menu_main":
        await query.edit_message_text(
            "Username bhejo ya Instagram/TikTok link paste karo!",
            reply_markup=InlineKeyboardMarkup([
                [InlineKeyboardButton("📥 Download Guide", callback_data="help")]
            ])
        )
        return
    
    if data.startswith("menu_"):
        await query.edit_message_text("Username bhejo ya profile link paste karo!")
        return
    
    if data.startswith("profile:"):
        username = data.split(":", 1)[1]
        await process_profile(update, context, username, is_callback=True)
        return
    
    if data.startswith("posts:"):
        username = data.split(":", 1)[1]
        await process_posts(update, context, username, is_callback=True)
        return
    
    if data.startswith("reels:"):
        username = data.split(":", 1)[1]
        await process_reels(update, context, username, is_callback=True)
        return
    
    if data.startswith("stories:"):
        username = data.split(":", 1)[1]
        await process_stories(update, context, username, is_callback=True)
        return
    
    if data.startswith("highlights:"):
        username = data.split(":", 1)[1]
        await process_highlights(update, context, username, is_callback=True)
        return
    
    if data.startswith("analytics:"):
        username = data.split(":", 1)[1]
        await process_analytics(update, context, username, is_callback=True)
        return

# ==================== LINK / MESSAGE HANDLER ====================
async def handle_text(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    text = (update.message.text or "").strip()
    
    if is_banned(user.id):
        return
    
    if not text:
        return
    
    await log_user_message(update, context)
    
    # TikTok
    if "tiktok.com" in text.lower() or "tiktok" in text.lower():
        await update.message.reply_chat_action("upload_video")
        await update.message.reply_text("⏳ TikTok video download ho raha hai...")
        
        info, filepath = await asyncio.get_event_loop().run_in_executor(
            executor, run_yt_dlp_download, text, None
        )
        
        if filepath and info:
            caption = f"✅ TikTok Downloaded!\n🎵 {info.get('title', 'No title')[:100]}\n👤 {info.get('uploader', 'Unknown')[:50]}"
            success = await safe_send_media(update, filepath, caption)
            if success:
                await log_download_success(update, context, text, filepath, info, is_tiktok=True)
            else:
                await update.message.reply_text("❌ File send nahi ho payi. Size badi ho sakti hai.")
                await log_download_failure(update, context, text, "Telegram send failed (file too large?)", is_tiktok=True)
        else:
            await update.message.reply_text("❌ TikTok download failed. Link check karo ya private video ho sakti hai.")
            await log_download_failure(update, context, text, filepath or "Unknown error", is_tiktok=True)
        return
    
    # Instagram
    if "instagram.com" in text.lower() or "instagr.am" in text.lower():
        # Profile URL detection
        profile_re = re.compile(r"https?://(?:www\.)?instagram\.com/([a-zA-Z0-9_.]{1,30})/?")
        match = profile_re.match(text)
        if match:
            username = match.group(1)
            if username not in ("p", "reel", "reels", "stories", "tv", "explore", "direct"):
                await show_profile_menu(update, username, context)
                return
        
        # Direct media (post, reel, story, etc.)
        await update.message.reply_chat_action("upload_video")
        await update.message.reply_text("⏳ Instagram download ho raha hai...")
        
        info, filepath = await asyncio.get_event_loop().run_in_executor(
            executor, run_yt_dlp_download, text, COOKIE_FILE
        )
        
        if filepath and info:
            caption = f"✅ Instagram Downloaded!"
            if info.get("title"):
                caption += f"\n📝 {info['title'][:200]}"
            if info.get("uploader"):
                caption += f"\n👤 {info['uploader']}"
            
            success = await safe_send_media(update, filepath, caption)
            if success:
                await log_download_success(update, context, text, filepath, info, is_tiktok=False)
            else:
                await update.message.reply_text("❌ File send nahi ho payi. Size badi ho sakti hai (max 50MB Telegram limit).")
                await log_download_failure(update, context, text, "Telegram send failed (file too large?)", is_tiktok=False)
        else:
            err_msg = (
                "❌ Download nahi hua.\n\n"
                "Possible reasons:\n"
                "• Instagram ne server IP block kiya ho\n"
                "• Content private ho\n"
                "• Link expired / invalid\n\n"
            )
            if not cookies_ready():
                err_msg += "💡 Cookie set karo: /setcookie"
            else:
                err_msg += "💡 Cookie expire ho gayi ho sakti hai. Update karo!"
            
            await update.message.reply_text(err_msg)
            await log_download_failure(update, context, text, filepath or "Unknown error", is_tiktok=False)
        return
    
    # If just a username without command
    if re.match(r"^[a-zA-Z0-9_.]{1,30}$", text):
        await show_profile_menu(update, text, context)
        return
    
    await update.message.reply_text("❌ Sirf Instagram ya TikTok links support hain!\n\n/help dekho for guide.")

# ==================== ADMIN COMMANDS ====================
async def stats_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not is_admin(update.effective_user.id):
        return
    
    uptime = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    cookie_status = "✅ Set" if cookies_ready() else "❌ Not Set"
    log_status = "✅ Active" if LOG_CHANNEL_ID else "❌ Not Set"
    
    text = (
        f"📊 <b>Bot Statistics</b>\n\n"
        f"🕒 Uptime: {uptime}\n"
        f"🍪 Cookie: {cookie_status}\n"
        f"📢 Log Channel: {log_status}\n"
        f"👑 Admins: {len(ADMIN_IDS)}\n"
        f"🚫 Banned: {len(BAN_LIST)}\n"
        f"🤖 Python: {sys.version.split()[0]}"
    )
    await update.message.reply_text(text, parse_mode="HTML")

async def broadcast_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not is_admin(update.effective_user.id):
        return
    if not context.args:
        await update.message.reply_text("Usage: /broadcast message")
        return
    
    message = " ".join(context.args)
    await update.message.reply_text(f"Broadcast feature requires database. Message:\n{message}")

async def ban_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not is_admin(update.effective_user.id):
        return
    if not context.args:
        await update.message.reply_text("Usage: /ban user_id")
        return
    user_id = context.args[0]
    BAN_LIST.add(user_id)
    await update.message.reply_text(f"🚫 User {user_id} banned.")
    await send_log_text(context, f"🚫 <b>User banned</b> by admin {update.effective_user.id}: <code>{user_id}</code>")

async def unban_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not is_admin(update.effective_user.id):
        return
    if not context.args:
        await update.message.reply_text("Usage: /unban user_id")
        return
    user_id = context.args[0]
    BAN_LIST.discard(user_id)
    await update.message.reply_text(f"✅ User {user_id} unbanned.")
    await send_log_text(context, f"✅ <b>User unbanned</b> by admin {update.effective_user.id}: <code>{user_id}</code>")

# ==================== MAIN ====================
def main():
    init_cookies()
    start_health_server()
    
    app = Application.builder().token(BOT_TOKEN).build()
    
    # Commands
    app.add_handler(CommandHandler("start", start_cmd))
    app.add_handler(CommandHandler("help", help_cmd))
    app.add_handler(CommandHandler("setcookie", setcookie_cmd))
    app.add_handler(CommandHandler("profile", profile_cmd))
    app.add_handler(CommandHandler("posts", posts_cmd))
    app.add_handler(CommandHandler("reels", reels_cmd))
    app.add_handler(CommandHandler("stories", stories_cmd))
    app.add_handler(CommandHandler("highlights", highlights_cmd))
    app.add_handler(CommandHandler("analytics", analytics_cmd))
    
    # Admin commands
    app.add_handler(CommandHandler("stats", stats_cmd))
    app.add_handler(CommandHandler("broadcast", broadcast_cmd))
    app.add_handler(CommandHandler("ban", ban_cmd))
    app.add_handler(CommandHandler("unban", unban_cmd))
    
    # Callbacks & messages
    app.add_handler(CallbackQueryHandler(callback_handler))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_text))
    
    logger.info("🚀 Bot started! Waiting for messages...")
    app.run_polling()

if __name__ == "__main__":
    main()
